# version: '3.8'

services:
  # servicio 1: la base de datos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  # microservicio: pdf-service
  pdf-service:
    build:
      context: ./microservices/pdf-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./microservices/pdf-service/.env
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/app
    command: sh -c "alembic upgrade head && uvicorn pdf_service.main:app --app-dir src --host 0.0.0.0 --port ${PORT:-8080}"

volumes:
  postgres_data:
