version: '3.8'

services:
  # servicio 1: la base de datos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # microservicio: pdf-service
  pdf-service:
    build:
      context: ./microservices/pdf-service
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app

volumes:
  postgres_data:
