release: alembic upgrade head
web: uvicorn pdf_service.main:app --app-dir src --host 0.0.0.0 --port $PORT
# web: gunicorn pdf_service.main:app -k uvicorn.workers.UvicornWorker --chdir src --bind 0.0.0.0:$PORT --workers 2 --timeout 120
