import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header"
import { ResponsiveContextProvider } from "@/app/contexts/useResponsive";
import { SidebarContextProvider } from "@/app/contexts/useSidebar";
import { CreditsContextProvider } from "@/app/contexts/useCredits";
import { ThemeContextProvider } from "@/app/contexts/useTheme";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UniHorario",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeContextProvider>
        <ResponsiveContextProvider>
          <SidebarContextProvider>
            <CreditsContextProvider>
              <Header/>
              {children}
            </CreditsContextProvider>
          </SidebarContextProvider>
        </ResponsiveContextProvider>
      </ThemeContextProvider>
      </body>
    </html>
  );
}
