"""extend year

Revision ID: 5baf5beea04a
Revises: 05b7ba18fe8e
Create Date: 2026-03-02 16:01:11.047130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5baf5beea04a'
down_revision: Union[str, Sequence[str], None] = '05b7ba18fe8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_careers_career_key'), table_name='catalog_careers')
    op.create_index(op.f('ix_catalog_careers_career_key'), 'catalog_careers', ['career_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_careers_career_key'), table_name='catalog_careers')
    op.create_index(op.f('ix_catalog_careers_career_key'), 'catalog_careers', ['career_key'], unique=True)
    # ### end Alembic commands ###
