"""init schema

Revision ID: a3c613356179
Revises: 
Create Date: 2026-02-28 17:41:28.532706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c613356179'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_key', sa.String(length=128), nullable=False),
    sa.Column('faculty', sa.String(length=128), nullable=False),
    sa.Column('career', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_careers_career_key'), 'catalog_careers', ['career_key'], unique=True)
    op.create_table('years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_years_year'), 'years', ['year'], unique=False)
    op.create_table('career_curriculums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year_id', sa.UUID(), nullable=False),
    sa.Column('faculty', sa.String(length=128), nullable=False),
    sa.Column('school', sa.String(length=128), nullable=False),
    sa.Column('specialization', sa.String(length=128), nullable=False),
    sa.Column('study_plan', sa.String(length=32), nullable=False),
    sa.Column('academic_period', sa.String(length=32), nullable=False),
    sa.Column('date_printed', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_curriculums_lookup', 'career_curriculums', ['school', 'study_plan', 'academic_period'], unique=False)
    op.create_table('catalog_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_career_id', sa.UUID(), nullable=False),
    sa.Column('cycle_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_career_id'], ['catalog_careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_career_id', 'cycle_name', name='uq_catalog_cycle')
    )
    op.create_table('catalog_study_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_career_id', sa.UUID(), nullable=False),
    sa.Column('study_plan', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_career_id'], ['catalog_careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_career_id', 'study_plan', name='uq_catalog_study_plan')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_curriculum_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_curriculum_id'], ['career_curriculums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('assignment', sa.String(length=256), nullable=False),
    sa.Column('assignment_id', sa.String(length=32), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.String(length=128), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('study_plan', sa.String(length=32), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('course_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'section_number', 'cycle_id', name='uq_course_sections_assignment_section_cycle')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_section_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('schedule_number', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_section_id', 'schedule_number', 'day', 'start_time', name='uq_schedules_section_schedule_day_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('course_sections')
    op.drop_table('cycles')
    op.drop_table('catalog_study_plans')
    op.drop_table('catalog_cycles')
    op.drop_index('ix_career_curriculums_lookup', table_name='career_curriculums')
    op.drop_table('career_curriculums')
    op.drop_index(op.f('ix_years_year'), table_name='years')
    op.drop_table('years')
    op.drop_index(op.f('ix_catalog_careers_career_key'), table_name='catalog_careers')
    op.drop_table('catalog_careers')
    # ### end Alembic commands ###
